apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    app: product
spec:
  replicas: 2
  selector:
    matchLabels:
       app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
          - name: product
            image: "dwape/products"
            ports:
              - containerPort: 80
            env:
              - name: DB_USER
                valueFrom:
                  configMapKeyRef:
                     name: db-config
                     key: db_user
              - name: DB_PASSWORD
                valueFrom:
                  configMapKeyRef:
                     name: db-config
                     key: db_password