apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation
  labels:
    app: recommendation
spec:
  replicas: 2
  selector:
    matchLabels:
       app: recommendation
  template:
    metadata:
      labels:
        app: recommendation
    spec:
      containers:
          - name: recommendation
            image: "dwape/recommendations"
            ports:
              - containerPort: 80
            env:
              - name: DB_USER
                valueFrom:
                  configMapKeyRef:
                     name: db-config
                     key: db_user
              - name: DB_PASSWORD
                valueFrom:
                  configMapKeyRef:
                     name: db-config
                     key: db_password