apiVersion: v1
kind: Service
metadata: 
  name: user-service
  labels:
    app: user
spec:
  selector:
    app: user
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
