apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
spec:
  replicas: 2
  selector:
    matchLabels:
       app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
          - name: user
            image: "user:v1"
            ports:
              - containerPort: 80
            env:
              - name: DB_USER
                valueFrom:
                  configMapKeyRef:
                     name: db-config
                     key: db_user
              - name: DB_PASSWORD
                valueFrom:
                  configMapKeyRef:
                     name: db-config
                     key: db_password

