apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist
  labels:
    app: wishlist
spec:
  replicas: 2
  selector:
    matchLabels:
       app: wishlist
  template:
    metadata:
      labels:
        app: wishlist
    spec:
      containers:
          - name: wishlist
            image: "dwape/wishlist"
            ports:
              - containerPort: 80
            env:
              - name: DB_USER
                valueFrom:
                  configMapKeyRef:
                     name: db-config
                     key: db_user
              - name: DB_PASSWORD
                valueFrom:
                  configMapKeyRef:
                     name: db-config
                     key: db_password